export { ReactComponent as TrashIcon } from "../../../utils/assets/SVG/bxs-trash.svg";
export { ReactComponent as EditIcon } from "../../../utils/assets/SVG/bxs-edit.svg";
export { ReactComponent as ChevronDown } from "../../../utils/assets/SVG/bxs-chevron-down.svg";
export { ReactComponent as SearchIcon } from "../../../utils/assets/SVG/bx-search-alt-2.svg";
export { ReactComponent as PlusIcon } from "../../../utils/assets/SVG/bx-plus.svg";
export { ReactComponent as MenuIcon } from "../../../utils/assets/SVG/bx-menu.svg";
export { ReactComponent as ContentIcon } from "../../../utils/assets/SVG/bxs-book-content.svg";
export { ReactComponent as ChevronDownSquareIcon } from "../../../utils/assets/SVG/bxs-chevron-down-square.svg";
export {ReactComponent as SunIcon} from "../../../utils/assets/SVG/bxs-sun.svg";
export {ReactComponent as MoonIcon} from "../../../utils/assets/SVG/bxs-moon.svg";
export {ReactComponent as LogOutIcon} from "../../../utils/assets/SVG/bx-log-out-circle.svg";
export {ReactComponent as EnvelopeIcon} from "../../../utils/assets/SVG/bx-envelope.svg";
export {ReactComponent as UserIcon} from "../../../utils/assets/SVG/bx-user.svg";
export {ReactComponent as LockIcon} from "../../../utils/assets/SVG/lock-svgrepo-com.svg";
export {ReactComponent as ArrowBackIcon} from "../../../utils/assets/SVG/bx-left-arrow-circle.svg";